export const faculties = {
  arts: [
    "English",
    "European Languages & Integration Studies",
    "History & Strategic Studies",
    "Linguistics African Asian Studies",
    "Philosophy",
  ],
  medicalSciences: [
    "Anatomic & Molecular Pathology",
    "Biochemistry",
    "Medical Microbiology & Parasitology",
    "Medical Laboratory Science",
    "Physiology",
  ],
  education: [
    "Arts & Social Science",
    "Human Kinetics & Health",
    "Education Administration",
    "Educational Foundations",
    "Science & Tech.",
  ],
  engineering: [
    "Chemical Engineering",
    "Civil & Environmental",
    "Electrical & Electronics",
    "Mechanical Engineering",
    "Metallurgical & Materials",
    "Petroleum and Gas",
    "Surveying & Geo-Informatics",
    "Systems Engineering",
  ],
  law: ["Law"],
  environmental: [
    "Architecture",
    "Building",
    "Estate",
    "Quantity Surveying",
    "Urban & Regional Planning",
  ],
  bizAdd: [
    "Accounting",
    "Actuarial Science & Insurance",
    "Banking & Finance",
    "Business Administration",
    "Industrial Relations & Personnel Management",
  ],
  sciences: [
    "Biochemistry",
    "Botany",
    "Cell Biology & Genetics",
    "Chemistry",
    "Computer Sciences",
    "Geosciences",
    "Mathematics",
    "Marine Science",
    "Microbiology",
    "Physics",
    "Zoology",
  ],
  socialSciences: [
    "Economics",
    "Geography",
    "Mass Communication",
    "Psychology",
    "Political Science",
    "Sociology",
  ],
};
