export const faculties = {
  arts: [
    "English",
    "European Languages & Integration Studies",
    "History & Strategic Studies",
    "Linguistics African Asian Studies",
    "Philosophy",
  ],
  medicalSciences: [
    "Anatomic & Molecular Pathology",
    "Biochemistry",
    "Medical Microbiology & Parasitology",
    "Medical Laboratory Science",
    "Physiology",
  ],
  education: [
    "Arts & Social Science",
    "Human Kinetics & Health",
    "Education Administration",
    "Educational Foundations",
    "Science & Tech.",
  ],
  engineering: [
    "Chemical Engineering",
    "Civil & Environmental",
    "Electrical & Electronics",
    "Mechanical Engineering",
    "Metallurgical & Materials",
    "Petroleum and Gas",
    "Surveying & Geo-Informatics",
    "Systems Engineering",
  ],
  law: ["Law"],
  environmental: [
    "Architecture",
    "Building",
    "Estate",
    "Quantity Surveying",
    "Urban & Regional Planning",
  ],
  bizAdd: [
    "Accounting",
    "Actuarial Science & Insurance",
    "Banking & Finance",
    "Business Administration",
    "Industrial Relations & Personnel Management",
  ],
  science: [
    "Biochemistry",
    "Botany",
    "Cell Biology & Genetics",
    "Chemistry",
    "Computer Sciences",
    "Geosciences",
    "Mathematics",
    "Marine Science",
    "Microbiology",
    "Physics",
    "Zoology",
  ],
  socialScience: [
    "Economics",
    "Geography",
    "Mass Communication",
    "Psychology",
    "Political Science",
    "Sociology",
  ],
};

export const newStudents = [
  {
    matricNo: 160403048,
    full_name: "Adelakun Oluwatobiloba Ayomipo",
    department: "Electrical & Electronics ",
    faculty: "Engineering",
    email: "adelakuntobiloba@gmail.com",
    country_code: "234",
    phone_number: "08168527167",
    gender: "Male",
    dob: "2000-04-03",
    address: "No 2, Oke Ola Street, Ibadan",
    created_at: "2023-06-25T03:35:14.336+00:00",
  },
  {
    matricNo: 180807002,
    full_name: "Ogunmilade Busayo Temilola",
    department: "Microbiology",
    faculty: "Sciecne",
    email: "adelakuntobiloba@gmail.com",
    country_code: "234",
    phone_number: "08168527167",
    gender: "Male",
    dob: "2000-04-03",
    address: "No 2, Oke Ola Street, Ibadan",
    created_at: "2023-06-25T03:35:14.336+00:00",
  },
  {
    matricNo: 160403048,
    full_name: "Adelakun Oluwatobiloba Ayomipo",
    department: "Electrical & Electronics ",
    faculty: "Engineering",
    email: "adelakuntobiloba@gmail.com",
    country_code: "234",
    phone_number: "08168527167",
    gender: "Male",
    dob: "2000-04-03",
    address: "No 2, Oke Ola Street, Ibadan",
    created_at: "2023-06-25T03:35:14.336+00:00",
  },
];
